steps:
  - id: "CI-CD Pipeline build"
    name: "ubuntu"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "CI/CD Pipeline Started"

  - id: "Terraform Init"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform init

  - id: "Terraform Fmt"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform fmt -check

  - id: "Terraform Validate"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform validate

  - id: "Terraform Plan"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform plan -out=tfplan

  - id: "Terraform Apply"
    name: "hashicorp/terraform:1.0.0"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" = "main" ]; then
          terraform apply -auto-approve tfplan
        else
          echo "Not on main branch. Skipping apply."
        fi

options:
  logging: CLOUD_LOGGING_ONLY

